"""initial schema

Revision ID: 42d59c43c1dd
Revises: 
Create Date: 2026-10-07 15:51:27.114805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d59c43c1dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('societies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('societies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_societies_name'), ['name'], unique=True)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_society_id'), ['society_id'], unique=False)

    op.create_table('maintenance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('affected_towers_json', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_events_society_id'), ['society_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_events_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_events_status'), ['status'], unique=False)

    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('inputs_json', sa.Text(), nullable=False),
    sa.Column('results_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_runs_society_id'), ['society_id'], unique=False)

    op.create_table('tanker_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_quantity_litres', sa.Float(), nullable=False),
    sa.Column('actual_quantity_litres', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tanker_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tanker_deliveries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tanker_deliveries_scheduled_arrival'), ['scheduled_arrival'], unique=False)
        batch_op.create_index(batch_op.f('ix_tanker_deliveries_society_id'), ['society_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tanker_deliveries_status'), ['status'], unique=False)

    op.create_table('tanks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('capacity_litres', sa.Float(), nullable=False),
    sa.Column('critical_reserve_litres', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tanks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tanks_society_id'), ['society_id'], unique=False)

    op.create_table('towers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('society_id', 'name')
    )
    with op.batch_alter_table('towers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_towers_society_id'), ['society_id'], unique=False)

    op.create_table('flats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tower_id', sa.Integer(), nullable=False),
    sa.Column('flat_number', sa.String(length=20), nullable=False),
    sa.Column('household_type', sa.String(length=40), nullable=False),
    sa.Column('occupant_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tower_id'], ['towers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flats_flat_number'), ['flat_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_flats_tower_id'), ['tower_id'], unique=False)

    op.create_table('tank_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('water_level_litres', sa.Float(), nullable=False),
    sa.Column('level_percent', sa.Float(), nullable=False),
    sa.Column('inflow_litres_per_minute', sa.Float(), nullable=False),
    sa.Column('outflow_litres_per_minute', sa.Float(), nullable=False),
    sa.Column('pump_state', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tank_readings', schema=None) as batch_op:
        batch_op.create_index('ix_tank_reading_tank_time', ['tank_id', 'observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tank_readings_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tank_readings_tank_id'), ['tank_id'], unique=False)

    op.create_table('meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flat_id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial')
    )
    with op.batch_alter_table('meters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meters_flat_id'), ['flat_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('flat_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=False),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaints_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_resident_id'), ['resident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_society_id'), ['society_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_status'), ['status'], unique=False)

    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_litres', sa.Float(), nullable=False),
    sa.Column('flow_litres_per_minute', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meter_readings', schema=None) as batch_op:
        batch_op.create_index('ix_meter_reading_meter_time', ['meter_id', 'observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_meter_readings_meter_id'), ['meter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meter_readings_observed_at'), ['observed_at'], unique=False)

    op.create_table('complaint_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaint_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_updates_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_updates_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_updates_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_updates_created_at'))
        batch_op.drop_index(batch_op.f('ix_complaint_updates_complaint_id'))
        batch_op.drop_index(batch_op.f('ix_complaint_updates_author_id'))

    op.drop_table('complaint_updates')
    with op.batch_alter_table('meter_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meter_readings_observed_at'))
        batch_op.drop_index(batch_op.f('ix_meter_readings_meter_id'))
        batch_op.drop_index('ix_meter_reading_meter_time')

    op.drop_table('meter_readings')
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_status'))
        batch_op.drop_index(batch_op.f('ix_complaints_society_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_resident_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_created_at'))

    op.drop_table('complaints')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('meters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meters_flat_id'))

    op.drop_table('meters')
    with op.batch_alter_table('tank_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tank_readings_tank_id'))
        batch_op.drop_index(batch_op.f('ix_tank_readings_observed_at'))
        batch_op.drop_index('ix_tank_reading_tank_time')

    op.drop_table('tank_readings')
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flats_tower_id'))
        batch_op.drop_index(batch_op.f('ix_flats_flat_number'))

    op.drop_table('flats')
    with op.batch_alter_table('towers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_towers_society_id'))

    op.drop_table('towers')
    with op.batch_alter_table('tanks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tanks_society_id'))

    op.drop_table('tanks')
    with op.batch_alter_table('tanker_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tanker_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_tanker_deliveries_society_id'))
        batch_op.drop_index(batch_op.f('ix_tanker_deliveries_scheduled_arrival'))
        batch_op.drop_index(batch_op.f('ix_tanker_deliveries_created_at'))

    op.drop_table('tanker_deliveries')
    with op.batch_alter_table('simulation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_runs_society_id'))

    op.drop_table('simulation_runs')
    with op.batch_alter_table('maintenance_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_events_status'))
        batch_op.drop_index(batch_op.f('ix_maintenance_events_start_time'))
        batch_op.drop_index(batch_op.f('ix_maintenance_events_society_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_maintenance_events_created_at'))

    op.drop_table('maintenance_events')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_society_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_level'))
        batch_op.drop_index(batch_op.f('ix_alerts_kind'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))

    op.drop_table('alerts')
    with op.batch_alter_table('societies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_societies_name'))

    op.drop_table('societies')
    # ### end Alembic commands ###
